Add native app authorisation protocol
FlickElectric/oauth2-provider pull request #4
Opened 2016-09-14 03:38 UTC by MichaelDowse

This is a fork of the original KB-Platform and SongKick gem. This fork has 2 basic motivations;

Add native app authorisation protocol to the standard OAuth2 protocol.
Perform a number of refactoring steps to improve the API and restructure some of the "big classes".
The primary reason for the fork is to add new native app protocols. This is based on draft RFC for native app OAuth, and also uses the Proof Key for Code Exchange scheme recommended for native application that support the "deep link" redirect approach.

As for the refactoring:

The new interface to obtain a parsed and process authorisation looks like this; OAuth2::Provider.parse(user, env).()
The overloaded initialize methods in provider/exchange.rb and provider/authorization.rb have been separated into different concerns.
These classes also have slightly more "dependency injected" validations.
The main token functions have been moved into a lib class SecureCodeScheme

2016-10-19 02:55 UTC, MichaelDowse commented
Diff with most of the changes but without the removal of Songkick which makes the diff hard to spot: https://github.com/FlickElectric/oauth2-provider/compare/master...FlickElectric:2a88a3e2695e8b1cb768210eb18ba9cd27df3a02

2016-11-28 04:12 UTC, josephleniston commented
Can we get some specs for the native app functionality and get the gem running on Travis. Also add some explanation of the new functionality.

2016-11-28 04:12 UTC, josephleniston requested changes

2016-11-28 04:12 UTC, josephleniston commented on Gemfile
> +source 'http://rubygems.org'
Needs to be changed back to `https`.

2016-11-28 04:12 UTC, josephleniston commented on lib/oauth2/lib/secure_code_scheme.rb
> +        id = send(tuple[1], attributes) until predicate_function(predicate).call(id)
change to
```ruby
        generation_method = case attributes[:code_type]
        when OPAQUE
          :random_string
        when PKCE
          :pkce_string
        else  # Shouldn't get here, but assume opaque
          :random_string
        end
        id = send(generation_method, attributes) until predicate_function(predicate).call(id)
        id
```

2016-11-28 04:12 UTC, josephleniston commented on lib/oauth2/lib/secure_code_scheme.rb
> +        cipher.iv = "aa8dbfb30de9bac490cab3aa551376add3462bb9080e0d534f8301cd094f56a7"
These keys should not be embedded they should be in an environment variable.

2016-11-28 04:12 UTC, josephleniston commented on lib/oauth2/lib/secure_code_scheme.rb
> +        cipher.update(Base64.urlsafe_decode64(code)) + cipher.final  rescue [nil, nil]
this should rescue a specific exception not any exception.

2016-11-28 04:12 UTC, josephleniston commented on lib/oauth2/lib/secure_code_scheme.rb
> +          SecureRandom.hex(TOKEN_SIZE / 8).to_i(16).to_s(36)
This should be required. Why would you want an insecure random?

2016-11-28 04:12 UTC, josephleniston commented on lib/oauth2/lib/secure_code_scheme.rb
> +        iss: 'https://id.flick.energy',
This should not be hardcoded. It should be an environment. This is duplicated in identity service so if this going in here then it should be referenced in identity service. This goes for all the values below.

2016-11-28 04:12 UTC, josephleniston commented on lib/oauth2/model/authorization.rb
> +          Helpers.count(self, :access_token_hash => hash).zero?
Why is this different to the test for existence inside `create_refresh_token` method?

2016-11-28 04:12 UTC, josephleniston commented on lib/oauth2/model/client.rb
> +        self.client_secret = OAuth2::Lib::SecureCodeScheme.random_string
You should call `.generate` here to be consistent with other code generation.

2016-11-28 04:12 UTC, josephleniston commented on lib/oauth2/provider.rb
> +    # end
Remove commented code.

2016-11-28 04:12 UTC, josephleniston commented on lib/oauth2/provider/authorization.rb
> +          ->(code) {true}
Are you sure this should always return true?

2016-12-06 00:03 UTC, MichaelDowse commented on Gemfile
> +source 'http://rubygems.org'
Change this back

2016-12-06 00:03 UTC, MichaelDowse commented on README.rdoc
> += OAuth2::Provider
Need to add to our travis

2016-12-06 00:03 UTC, MichaelDowse commented on LICENSE
> +Copyright (c) 2016 Flick
Here and below this should be `Flick Electric Co.`

2016-12-06 00:03 UTC, MichaelDowse commented on README.rdoc
> +Copyright (c) 2016 FlickElectric.co.nz
Flick Electric Co.

2016-12-06 00:03 UTC, MichaelDowse commented on lib/oauth2/lib/secure_code_scheme.rb
> +        cipher.key = "bff19d8c59f31f68d70e34abae5c93420c17f50bc3c278878593ced6b03d916d"
These values probably shouldn't be in the repo

2016-12-06 00:03 UTC, MichaelDowse commented on lib/oauth2/lib/secure_code_scheme.rb
> +      def self.generate_id_token_hash(user)
Not sure this should exist in the library, something very similar already exists at the Identity Service level, can we use that? https://github.com/FlickElectric/identity_service/blob/master/app/models/oauth/token.rb

2016-12-06 00:03 UTC, MichaelDowse commented on lib/oauth2/model.rb
> +    # ActiveRecord::RecordNotUnique was introduced in Rails 3.0 so referring
Don't bother supporting rails versions < 3

2016-12-06 02:43 UTC, josephleniston commented on lib/oauth2/model/authorization.rb
> +          Helpers.count(self, :access_token_hash => hash).zero?
This is original code logic. Looks like refresh_tokens are scoped by client for some reason.

2016-12-07 02:00 UTC, merged